name: Publish to PyPI

on:
  push:
    branches:
      - main
    paths:
      - "**"
    commit_message:
      contains: release

jobs:
  publish-package:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Install Poetry
        run: pip install poetry

      - name: Build the package
        run: poetry build

      - name: Publish the package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          pypi_token: "${{secrets.PYPI_API_TOKEN}}"
