name: Publish to PyPI

on:
  push:
    tags:
      - "*"

jobs:
  publish:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version:
          - 3.8.x
          - 3.9.x
          - 3.10.x

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        run: |
          pip install poetry
          poetry install

      - name: Build and Publish
        run: |
          poetry build
          poetry publish --build
        env:
          POETRY_PYPI_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
